# Generated by Django 5.2.7 on 2025-11-01 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_matiere', models.CharField(max_length=20, unique=True, verbose_name='Code Matière')),
                ('nom_matiere', models.CharField(max_length=100, unique=True, verbose_name='Nom de la Matière')),
                ('heure_hebdomadaire', models.PositiveIntegerField(default=0, verbose_name='Heures Hebdomadaires')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_cree', to=settings.AUTH_USER_MODEL)),
                ('modifier_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_modifie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom_matiere'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Création', 'Création'), ('Modification', 'Modification'), ('Suppression', 'Suppression')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='matieres.matiere')),
            ],
            options={
                'verbose_name': 'Historique Matière',
                'verbose_name_plural': 'Historique Matières',
                'ordering': ['-date_action'],
            },
        ),
    ]
