# Generated by Django 5.2.7 on 2025-10-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_matiere', models.CharField(max_length=20, unique=True, verbose_name='Code Matière')),
                ('nom_matiere', models.CharField(max_length=100, unique=True, verbose_name='Nom de la Matière')),
                ('heure_hebdomadaire', models.PositiveIntegerField(default=0, verbose_name='Heures Hebdomadaires')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom_matiere'],
            },
        ),
    ]
