# Generated by Django 5.2.1 on 2025-11-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='code_matiere',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code Matière'),
        ),
    ]
