# Generated by Django 5.2.8 on 2025-11-30 18:07

import annee_scolaire.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annee_scolaire', '0001_initial'),
        ('classes', '0002_auto_20251024_1037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('adresse', models.TextField()),
                ('niveau', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('radié', 'Radié'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/photos/', verbose_name='Photo')),
                ('date_inscription', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='annee_scolaire.anneescolaire', verbose_name='Année scolaire')),
                ('classe_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_actuels', to='classes.classe')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'unique_together': {('matricule', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('inscription', 'Nouvelle inscription'), ('changement_classe', 'Changement de classe'), ('suspension', 'Suspension'), ('reprise', 'Reprise des cours'), ('graduation', 'Diplômé'), ('discipline', 'Mesure disciplinaire'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('annee_scolaire', models.ForeignKey(default=annee_scolaire.models.AnneeScolaire.get_annee_courante, on_delete=django.db.models.deletion.CASCADE, to='annee_scolaire.anneescolaire')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_eleves', to='eleves.eleve')),
            ],
        ),
    ]
