# Generated by Django 5.2.7 on 2025-11-01 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('inscription', 'Nouvelle inscription'), ('changement_classe', 'Changement de classe'), ('suspension', 'Suspension'), ('reprise', 'Reprise des cours'), ('graduation', 'Diplômé'), ('discipline', 'Mesure disciplinaire'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_eleves', to='eleves.eleve')),
            ],
        ),
    ]
