# Generated by Django 5.2.7 on 2025-10-25 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='date_inscription',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'inscription"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, default='eleves/photos/default_avatar.png', null=True, upload_to='eleves/photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('radié', 'Radié'), ('suspendu', 'Suspendu')], default='actif', max_length=20),
        ),
    ]
