# Generated by Django 5.2.1 on 2025-11-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_historiqueeleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/photos/', verbose_name='Photo'),
        ),
    ]
