# Generated by Django 5.2.7 on 2025-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_classe', models.CharField(max_length=20, unique=True, verbose_name='Code Classe')),
                ('nom_classe', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(choices=[('7ème', '7ème'), ('8ème', '8ème'), ('9ème', '9ème'), ('NSI', 'NSI'), ('NSII', 'NSII'), ('NSIII', 'NSIII'), ('NSIV', 'NSIV')], max_length=20, verbose_name='Niveau scolaire')),
                ('capacite_max', models.PositiveIntegerField(default=50, verbose_name='Capacité maximale')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'nom_classe'],
            },
        ),
    ]
