# Generated by Django 5.2.8 on 2025-11-30 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_auto_20251024_1037'),
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_classes', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Historique de Classe',
                'verbose_name_plural': 'Historiques de Classes',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'élève")),
                ('prenom', models.CharField(max_length=100, verbose_name="Prénom de l'élève")),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=255, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, verbose_name='Sexe')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('niveau', models.CharField(max_length=50, verbose_name='Niveau scolaire')),
                ('annee_scolaire', models.CharField(help_text='Format: AAAA-AAAA', max_length=9, verbose_name='Année scolaire')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('personne_responsable', models.CharField(max_length=255, verbose_name='Nom du responsable')),
                ('profession_responsable', models.CharField(max_length=100, verbose_name='Profession du responsable')),
                ('telephone_responsable', models.CharField(max_length=20, verbose_name='Téléphone du responsable')),
                ('email_responsable', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du responsable')),
                ('ecole_origine', models.CharField(blank=True, max_length=255, null=True, verbose_name="École d'origine")),
                ('statut', models.CharField(choices=[('pre-inscrit', 'Pré-inscrit'), ('validé', 'Validé'), ('actif', 'Actif'), ('refuse', 'Refusé')], default='pre-inscrit', max_length=20, verbose_name="Statut de l'inscription")),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='classes.classe', verbose_name='Classe choisie')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_crees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.eleve', verbose_name='Élève lié (si validé)')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_created'],
                'unique_together': {('nom', 'prenom', 'date_naissance', 'annee_scolaire')},
            },
        ),
    ]
