# Generated by Django 5.2.7 on 2025-10-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'élève")),
                ('prenom', models.CharField(max_length=100, verbose_name="Prénom de l'élève")),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=255, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, verbose_name='Sexe')),
                ('adresse', models.TextField(verbose_name='Adresse complète (rue, commune, département)')),
                ('niveau', models.CharField(max_length=50, verbose_name='Niveau scolaire')),
                ('annee_scolaire', models.CharField(help_text='Format: AAAA-AAAA (ex: 2025-2026)', max_length=9, verbose_name='Année scolaire')),
                ('personne_responsable', models.CharField(max_length=255, verbose_name='Nom de la personne responsable')),
                ('profession_responsable', models.CharField(max_length=100, verbose_name='Profession du responsable')),
                ('telephone_responsable', models.CharField(max_length=20, verbose_name='Téléphone du responsable')),
                ('email_responsable', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du responsable (optionnel)')),
                ('ecole_origine', models.CharField(blank=True, max_length=255, null=True, verbose_name="École d'origine (optionnel)")),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('pre-inscrit', 'Pré-inscrit'), ('validé', 'Validé'), ('aktif', 'Actif'), ('refize', 'Refusé')], default='pre-inscrit', max_length=20, verbose_name="Statut de l'inscription")),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='classes.classe', verbose_name='Classe choisie')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
