# Generated by Django 5.2.7 on 2025-11-01 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20251024_1037'),
        ('eleves', '0002_historiqueeleve'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_classes', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Historique de Classe',
                'verbose_name_plural': 'Historiques de Classes',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.DeleteModel(
            name='HistoriqueClasse',
        ),
    ]
