# Generated by Django 5.2.7 on 2025-10-24 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('inscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par (secrétaire)'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='eleve',
            field=models.OneToOneField(blank=True, help_text='Liye avèk dosye Eleve a lè enskripsyon an valide.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.eleve', verbose_name='Élève créé (si validé)'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('nom', 'prenom', 'date_naissance', 'annee_scolaire')},
        ),
    ]
