# Generated by Django 5.2.7 on 2025-10-28 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_eleve_date_inscription_eleve_photo_and_more'),
        ('inscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='eleve',
            field=models.OneToOneField(blank=True, help_text="lier avec les dossiers de l'eleves si les inscription sont valide.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.eleve', verbose_name='Élève créé (si validé)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='email_responsable',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email du responsable (optionnel)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='telephone_responsable',
            field=models.CharField(max_length=20, unique=True, verbose_name='Téléphone du responsable'),
        ),
    ]
