# Generated by ChatGPT: add date_debut and date_fin to HistoriqueClasses
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_add_missing_base_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueclasses',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historiqueclasses',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
