# Generated by Django 5.2.7 on 2025-10-30 21:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_eleve_date_inscription_eleve_photo_and_more'),
        ('inscriptions', '0003_alter_inscription_eleve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ['-date_created'], 'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='date_inscription',
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='annee_scolaire',
            field=models.CharField(help_text='Format: AAAA-AAAA', max_length=9, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='eleve',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.eleve', verbose_name='Élève créé (si validé)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='email_responsable',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du responsable (optionnel)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='telephone_responsable',
            field=models.CharField(max_length=20, verbose_name='Téléphone du responsable'),
        ),
    ]
