# Generated by Django 5.2.8 on 2025-11-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_add_historiquefields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiqueclasses',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Historique de Classe', 'verbose_name_plural': 'Historiques de Classes'},
        ),
        migrations.RemoveField(
            model_name='historiqueclasses',
            name='date_inscription',
        ),
    ]
