# Generated by Django 5.2.7 on 2025-10-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
          migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='telephone',
        ),
    ]
