# Generated by Django 5.2.7 on 2025-10-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_auto_20251030_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='telephone',
            new_name='phone',
        ),
    ]
