# Generated by Django 5.2.6 on 2025-11-10 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_customuser_photo_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inscription', 'Inscription'), ('action_secretaire', 'Action Secrétaire'), ('action_archives', 'Action Archives'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('systeme', 'Système'), ('validation', 'Validation')], default='systeme', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_url', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'utilisateurs_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
