# Generated by ChatGPT - add recipient_role, broadcast, nullable user and NotificationRecipient model
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='utilisateurs.customuser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='broadcast',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='utilisateurs.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='utilisateurs.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
