# Generated by Django 5.2.8 on 2025-11-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_alter_notificationrecipient_id_usersession'),
    ]

    operations = [
    ]
