# Generated by Django 5.2.6 on 2025-11-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_ensure_tables'),
    ]

    operations = [
    ]
