# Generated by Django 5.2.1 on 2025-11-26 22:19

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos/', validators=[utilisateurs.models.validate_image], verbose_name='Photo de profil'),
        ),
    ]
