# Generated by Django 5.2.7 on 2025-10-30 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        ('enseignants', '0001_initial'),
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignants.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matieres.matiere', verbose_name='Matière'),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('classe', 'jour', 'heure_debut'), name='unique_classe_creneau'),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('enseignant', 'jour', 'heure_debut'), name='unique_enseignant_creneau'),
        ),
    ]
