# Generated by Django 5.2.7 on 2025-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='annee_scolaire',
            field=models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], default='2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='cours',
            name='code_cours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code Cours'),
        ),
        migrations.AddField(
            model_name='cours',
            name='nb_heures_total',
            field=models.IntegerField(default=0, verbose_name="Nombre d'heures total"),
        ),
        migrations.AddField(
            model_name='cours',
            name='semestre',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=10, verbose_name='Jour'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='planifie', max_length=20),
        ),
    ]
