# Generated by Django 5.2.7 on 2025-10-30 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('diplome', models.CharField(blank=True, max_length=150, null=True)),
                ('date_recrutement', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enseignants/photos/')),
                ('matieres', models.ManyToManyField(blank=True, related_name='enseignants', to='matieres.matiere', verbose_name='Matières enseignées')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
    ]
