# Generated by Django 5.2.7 on 2025-11-01 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matieres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialite', models.CharField(max_length=100)),
                ('diplome', models.CharField(max_length=100)),
                ('date_recrutement', models.DateField()),
                ('statut', models.CharField(default='actif', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enseignants/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants_crees', to=settings.AUTH_USER_MODEL)),
                ('matieres', models.ManyToManyField(blank=True, to='matieres.matiere')),
                ('modifier_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nom', 'prenom')},
            },
        ),
    ]
