# Generated by Django 5.2.7 on 2025-11-04 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0001_initial'),
        ('matieres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseignant',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Enseignant', 'verbose_name_plural': 'Enseignants'},
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='date_naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='date_recrutement',
            field=models.DateField(verbose_name='Date de recrutement'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='diplome',
            field=models.CharField(max_length=100, verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='lieu_naissance',
            field=models.CharField(max_length=150, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='matieres',
            field=models.ManyToManyField(blank=True, to='matieres.matiere', verbose_name='Matières enseignées'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='modifier_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='enseignants/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(max_length=100, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('archive', 'Archivé'), ('conge', 'En congé')], default='actif', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='telephone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Téléphone'),
        ),
    ]
