# Generated by Django 5.2.8 on 2025-11-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0002_alter_enseignant_options_alter_enseignant_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Matricule'),
        ),
    ]
